# -*- coding: utf-8 -*-
"""
Created on Tue Sep 17 12:01:44 2019

@author: nurrim064119
"""

dataset = {'ANI': {'Ada Apa dengan Cinta 2': 4.0,
  'Aladdin': 4.0,
  'Avengers: End Game': 0.0,
  'Bumi Manusia ': 5.0,
  'Captain Marvel': 4.0,
  'Dilan 1991': 4.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 3.0,
  'The Lion King': 0.0},
 'AhokTemanFirli': {'Ada Apa dengan Cinta 2': 0.0,
  'Aladdin': 0.0,
  'Avengers: End Game': 3.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 4.0,
  'Dilan 1991': 0.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 0.0,
  'The Lion King': 0.0},
 'Damar Teman Firli': {'Ada Apa dengan Cinta 2': 5.0,
  'Aladdin': 0.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 0.0,
  'Dilan 1991': 0.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 5.0,
  'The Lion King': 0.0},
 'Dpv': {'Ada Apa dengan Cinta 2': 5.0,
  'Aladdin': 0.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 5.0,
  'Dilan 1991': 4.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 4.0,
  'Spiderman: Far From Home': 5.0,
  'The Lion King': 0.0},
 'Febi ganteng gak ada obat': {'Ada Apa dengan Cinta 2': 4.0,
  'Aladdin': 5.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 4.0,
  'Dilan 1991': 4.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 3.0,
  'Spiderman: Far From Home': 5.0,
  'The Lion King': 0.0},
 'Genjeh': {'Ada Apa dengan Cinta 2': 5.0,
  'Aladdin': 5.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 4.0,
  'Dilan 1991': 3.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 4.0,
  'Spiderman: Far From Home': 4.0,
  'The Lion King': 0.0},
 'Hania': {'Ada Apa dengan Cinta 2': 3.0,
  'Aladdin': 0.0,
  'Avengers: End Game': 0.0,
  'Bumi Manusia ': 4.0,
  'Captain Marvel': 0.0,
  'Dilan 1991': 4.0,
  'Dua Garis Biru': 4.0,
  'Gundala': 5.0,
  'Spiderman: Far From Home': 0.0,
  'The Lion King': 0.0},
 'Indra 1991 SM': {'Ada Apa dengan Cinta 2': 0.0,
  'Aladdin': 0.0,
  'Avengers: End Game': 0.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 0.0,
  'Dilan 1991': 0.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 5.0,
  'Spiderman: Far From Home': 0.0,
  'The Lion King': 0.0},
 'Indra Junior': {'Ada Apa dengan Cinta 2': 4.0,
  'Aladdin': 5.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 5.0,
  'Dilan 1991': 0.0,
  'Dua Garis Biru': 4.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 5.0,
  'The Lion King': 5.0},
 'Jawaharal': {'Ada Apa dengan Cinta 2': 2.0,
  'Aladdin': 5.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 4.0,
  'Dilan 1991': 3.0,
  'Dua Garis Biru': 5.0,
  'Gundala': 4.0,
  'Spiderman: Far From Home': 5.0,
  'The Lion King': 4.0},
 'Maria O.': {'Ada Apa dengan Cinta 2': 0.0,
  'Aladdin': 4.0,
  'Avengers: End Game': 0.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 0.0,
  'Dilan 1991': 0.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 0.0,
  'The Lion King': 5.0},
 'Mulya': {'Ada Apa dengan Cinta 2': 0.0,
  'Aladdin': 5.0,
  'Avengers: End Game': 4.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 3.0,
  'Dilan 1991': 0.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 4.0,
  'The Lion King': 2.0},
 'Nonton_Saat_Diskon': {'Ada Apa dengan Cinta 2': 4.0,
  'Aladdin': 5.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 5.0,
  'Dilan 1991': 3.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 3.0,
  'Spiderman: Far From Home': 4.0,
  'The Lion King': 5.0},
 'OM INDRA': {'Ada Apa dengan Cinta 2': 3.0,
  'Aladdin': 1.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 5.0,
  'Dilan 1991': 2.0,
  'Dua Garis Biru': 5.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 5.0,
  'The Lion King': 0.0},
 'Putrisqiana': {'Ada Apa dengan Cinta 2': 4.0,
  'Aladdin': 0.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 4.0,
  'Captain Marvel': 3.0,
  'Dilan 1991': 2.0,
  'Dua Garis Biru': 3.0,
  'Gundala': 3.0,
  'Spiderman: Far From Home': 4.0,
  'The Lion King': 0.0},
 'Rima': {'Ada Apa dengan Cinta 2': 5.0,
  'Aladdin': 5.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 4.0,
  'Captain Marvel': 5.0,
  'Dilan 1991': 5.0,
  'Dua Garis Biru': 3.0,
  'Gundala': 5.0,
  'Spiderman: Far From Home': 5.0,
  'The Lion King': 4.0},
 'Romantika': {'Ada Apa dengan Cinta 2': 5.0,
  'Aladdin': 0.0,
  'Avengers: End Game': 0.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 0.0,
  'Dilan 1991': 5.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 0.0,
  'The Lion King': 0.0},
 'Star': {'Ada Apa dengan Cinta 2': 4.0,
  'Aladdin': 5.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 5.0,
  'Dilan 1991': 0.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 4.0,
  'Spiderman: Far From Home': 0.0,
  'The Lion King': 5.0},
 'Topik Zulkarnain': {'Ada Apa dengan Cinta 2': 0.0,
  'Aladdin': 0.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 2.0,
  'Dilan 1991': 0.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 4.0,
  'The Lion King': 5.0},
 'bunga': {'Ada Apa dengan Cinta 2': 0.0,
  'Aladdin': 5.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 5.0,
  'Dilan 1991': 4.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 4.0,
  'Spiderman: Far From Home': 5.0,
  'The Lion King': 5.0},
 'faizah': {'Ada Apa dengan Cinta 2': 3.0,
  'Aladdin': 0.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 5.0,
  'Captain Marvel': 0.0,
  'Dilan 1991': 5.0,
  'Dua Garis Biru': 4.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 0.0,
  'The Lion King': 0.0},
 'franadek': {'Ada Apa dengan Cinta 2': 4.0,
  'Aladdin': 5.0,
  'Avengers: End Game': 5.0,
  'Bumi Manusia ': 5.0,
  'Captain Marvel': 4.0,
  'Dilan 1991': 4.0,
  'Dua Garis Biru': 3.0,
  'Gundala': 4.0,
  'Spiderman: Far From Home': 4.0,
  'The Lion King': 4.0},
 'jul': {'Ada Apa dengan Cinta 2': 0.0,
  'Aladdin': 3.0,
  'Avengers: End Game': 3.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 3.0,
  'Dilan 1991': 0.0,
  'Dua Garis Biru': 3.0,
  'Gundala': 3.0,
  'Spiderman: Far From Home': 3.0,
  'The Lion King': 3.0},
 'luck': {'Ada Apa dengan Cinta 2': 3.0,
  'Aladdin': 0.0,
  'Avengers: End Game': 4.0,
  'Bumi Manusia ': 0.0,
  'Captain Marvel': 2.0,
  'Dilan 1991': 0.0,
  'Dua Garis Biru': 0.0,
  'Gundala': 0.0,
  'Spiderman: Far From Home': 0.0,
  'The Lion King': 0.0}}